### ISSUE TITLE
Lettura informazioni dai file csv

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#11]
La funzione dovrà leggere le informazioni che gli verranno richieste attraverso i file csv di trentino trasporti e poi restituire le informazioni al richiedente.
Le informazioni possono essre un'intera tabella oraria come anche solamente la prossima corsa disponibile
Possiamo filtrare per l'inea o per fermata oppure entrambe

HOW TO TEST: richiedere la tabella oraria di una singola fermata (dovrà comprendere tutte le linee) richiedere la tabella oraria di una singola linea (Dovrà comprendere orari e fermate) richiedere la tabella oraria di una linea ad una determinata fermata (dovrà restituire la tabella che è presente nella fermata della singola linea)

**Comment by iAndrea** [comment]
Funzione completata, al momento però il database viene aggiornato solo su "richiesta" e non settimanalmente
