### ISSUE TITLE
Implementazione api google maps

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#12]
Implementazione api di google maps in modo da richiedere informazioni per quanto riguarda la posizione delle fermate
Quando si cerca la fermata più vicina data la posizione attuale.
Dovrà essre possibile utilizzare le informazioni ottenibili dalla funzione che legge i csv per poter filtrare i risultati

HOW TO TEST: bisognerà testare inviando posizione fittizzie e riconoscere le fermate che ci interessano, eseguire un doppio controllo ricontrollando le coordinate ottenute su google maps
Ripetere il test applicando i filtri delle fermate dei csv che ci fornisce l'apposita funzione

**Comment by iAndrea** [comment]
Essendo le fermate molto vicine le une dalle altre, ho optato per riconoscere le più vicine in linea d'aria, senza così dover implementare delle API aggiuntive
