### ISSUE TITLE
Ottere l'orario del prossimo autobus data una 

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#13]
Cercare il prossimo autobus considerando però anche la possibilità di utilizzare la posizione per filtrare i risultati, cercando il prossimo autobus di una linea specifica alla fermata più vicina.
La funzione dovrà restituire come risultato il prossimo autobus interrogando i csv e la geolocalizzazione in un unico semplice messaggio json

HOW TO TEST: richiedere l'autobus più vicinoo fornendo posizione e linea desiderata, leggere il json ritornato.
Controllare i dati ritornati con i dati presenti su google maps per la posizione

**Comment by iAndrea** [comment]
Funzione completata, utilizzando il db per trovare le prima tratte
