### ISSUE TITLE
Percorsi attraverso le api di google maps

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#14]
Creare una funzione che permetta dati un punto di partenza ed un punto di arrivo fornire informazioni su di un percorso possibile per raggiungere la destinazione con i mezzi pubblici come autobus e treni
La funzione se possibile dovrà permettere l'interpretazione dall'esterno dei percorsi

HOW TO TEST: selezionare un percorso su google maps, dando una partenza ed un arrivo dopo di che prendere gli stessi punti e sottoporli alla funzione, controllare che fornisca gli stessi valori

**Comment by iAndrea** [comment]
Ancora una volta, senza scomodare le api di google maps, mi limito a inviare la posizione della fermata prescelta all'utente. Telegram, grazie all'integrazione con il sistema operativo, già mostra il pulsante per ottenere le indicazioni stradali per raggiungere un percorso.
