### ISSUE TITLE
Ottenre il percorso migliore per raggiungere una destinazione con filtri mezzi pubblici

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#15]
La funzione dovrà permettere di utilizzare i filtri ottenuti dai csv per poi poterli applicare al percorso suggerito dalle api di google maps, compreso il fatto di poter selezionare la fermata più vicina ed una derminata linea
Questa funzione rappresenta un pò l'utilizzo di tutte le altre già create per i trasporti, infatti permette di applicare filtri, di utilizzare google maps e di utilizzare l'orario del prossimo autobus.

i dati dovranno essre ritornati in modo tale da poterli rappresentare sia nel bot che nel browser web

HOW TO TEST: impostare tutti i filtri provando ogni singola combinazione e accertarsi dei risultati con l'aiuto di google maps e trentino trasporti.

**Comment by iAndrea** [comment]
La funzione è stata completata sfruttando unicamente il db di tte e non google maps
