### ISSUE TITLE
Ottenere scadenze

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#22]
Creare una funzione che restituisce le scadenze che sono presenti nei vari bandi, come quello per la borsa di studi ecc, la risposta dovrà essere data in formato JSON, in input si avrà il tipo di scadenza che si desidera ottenere (Borsa di studi/Posto alloggio/ecc) le informazioni dovranno essere concise ma esaustive

HOW TO TEST: fare una richiesta alla funzione specificando uno per volta i vari tipi di scadenze, controllare con un lettore di JSON la correttezza dei risultati

**Comment by Brugix** [comment]
Feature completata. Tuttavia, l'aggiornamento dei dati trasmessi deve essere eseguito manualmente.
