### ISSUE TITLE
Scadenza specifica 

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#23]
(Funzione non certa, da verificarsi la possibilità di implementarla effettivamente)

Impostare tramite bot una specifica scadenza da parte dell'utente in modo che poi possa essere ricordata il giorno primo per esempio.
L'utente imposterà un titolo, un testo, un dateTime specifico, dopo di che dovrà essre salvato sul database

**Comment by Brugix** [comment]
Non è stato possibile realizzare questa funzione a causa di problemi implementativi.
