### ISSUE TITLE
Funzione che mostra determinati documenti

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#24]
Una funzione che restituisce i documenti richiesti dall'utente in una specifica sezione (Opera universitaria/Erasmus/ecc) la funzione prima dovrà cercare nella cache del server, se i file pdf non verranno trovati allora attraverso un weapper andranno richiesti alla pagina.
Se possibile oltre al file andranno mostrate anche le informazioni ottenute dalla funzione scadenze di quel bando specifico

HOW TO TEST: Richiedere un tipo di documento specifico e controllare il file ottenuto

**Comment by iAndrea** [comment]
Sezione eliminata dal progetto
