### ISSUE TITLE
Funzione che ottiene documenti con input generico

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#25]
Modificare la funzione precedente della richeista documenti in modo che possa restituire dei documenti specifici in base all'input che rappresenterà la categoria di documenti.

HOW TO TEST: fare svariate richieste specifiche alla funzione differenziando il tipo di input

**Comment by iAndrea** [comment]
Funzione eliminata dal progetto
