### ISSUE TITLE
Funzione avvisi

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#26]
Creare una funzione che legga i feedRss della pagina degli avvisi dell'università, questa funzione avrà in input la facoltà e se possibile il corso di studi di cui mostrare gli avvisi. gli avvisi mostrati sono solo quelli del giorno in corso.
I dati dovranno essere restituiti in formato JSON

NON sarà possibile selezionare un corso di studi non presente in una determinata facoltà.

HOW TO TEST: Richiedere degli avvisi dando facoltà e corso di studi e controllare con un lettore di JSON che il risultato sia pertienete a ciò che è presente nella pagina degli avvisi di ateneo. controllare facoltà diverse.

**Comment by Brugix** [comment]
La funzione prende in input il dipartimento richiesto e restituisce (dopo aver effettuato un parsing della pagina avvisi) un JSON contenente gli avvisi del giorno corrente.
