### ISSUE TITLE
Funzione corso di studi

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#27]
Funzione che dato in input la facoltà ne restituisce tramite JSON i corsi di studi presenti.
La funzione verrà utilizzata dalla sezione AVVISI principalmente ma implementazioni di nuove funzioni potrebbero richiederne l'utilizzo, tenerne conto durante la creazione.

HOW TO TEST: Richiedere una facoltà, leggere il file JSON restituito e controllare la veridicità con il sito internet di quella specifica facoltà

**Comment by Brugix** [comment]
Non è stato possibile implementare questa funzione poiché solamente alcuni dipartimenti hanno una pagina avvisi.
Inoltre questi avvisi non sono suddivisi per corso di studi, rendendo così altamente complesso il riconoscimento di avvisi specifici ad un relativo corso di studi.
