### ISSUE TITLE
Mense più vicine

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#28]
Creare una funzione che sfrutti le api di google maps che dato in input la posizione attuale dell'utente mostri le mense più vicine.
I dati dovranno essere restituiti in JSON

HOW TO TEST: Inviare la propria posizione e utilizzare un lettore di JSON per controlarne il risultato

**Comment by iAndrea** [comment]
Sezione implementata correttamente
