### ISSUE TITLE
Ottenimento informazini sulla posizione attuale

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#29]
Creare una funzione che richieda la posizone attuale dell'utente, dovrà essere indifferete che l'utente utilizzi il bot telegram o il bot web.

La funzione sarà molto utile in diverse altre funzioni come per esempio TRASPORTI, se ne consiglia l'implementazione tendo conto del fattore di riutilizzo.

HOW TO TEST: inviare la propria posizone e controllarne la correttezza

**Comment by iAndrea** [comment]
funzione completata grazie alle API telegram
