### ISSUE TITLE
Telecamere Mensa

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#30]
Dovrà essere possibile ottenre lo stato attuale della mensa attraverso le telecamere.
In input si avrà quale telecamera si desidera visionare, in output si avrà un JSON contenete le informazioni della telecamera, posizione, quale mensa, e il link per vsionare l'immagine

HOW TO TEST: L'utente potrà richiedere varie mense in successione per cui andrà controllato il fatto che le informazini si aggiornino correttamente.

**Comment by iAndrea** [comment]
Non implementabile per motivi di copyright
