### ISSUE TITLE
BUG button telegram multiple position

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#37]
Utilizzando i button in line si è presentata una bug per ora solo in trasporti e luoghi utili.
i bottoni vengono utilizzati per mostrare i risultati della ricerca.
- Nel caso dei trasporti vengono mostrati 3 pulsanti corrispondenti alle 3 fermate più vicine e un pulsante che permette di ricevere la localizzazione della fermata scelta.
- Nel caso dei luoghi utili vengono mostrati n pulsanti (che scorrono) in modo che l'utente possa selezionare il posto che gli interessa, ed un pulsante invia posizione che manda la posizone del luogo attualmente scelto.

Il bug consiste nel fatto che la prima volta che si seleziono un luogo/fermata e dopo di che la posizione funziona correttamente ed invia la posizione una sola volta.
Una volta però tornati nella sezione trasporti/luoghi utili e selezionato un'altro luogo/autobus (O anche lo stesso) il bug si differenzia:
- per i trasporti i pulsanti sono 3 quindi la selezione funziona correttamente (Da controllare quale autobus venga mostrato, dubbio che venga mostrato quello della linea selezionata precedentemente) una volta richiesta la posizone però esse viene inviata 2 volte. (sospetto che la prima posizione inviata corrisponda alla fermata 1/2/3 della linea scelta precedentemente mentre la seconda posizione appartenga alla fermata 1/2/3 selezionata con la seconda linea)
- per la sezione luoghi utili il bug si presenta già nei pulsanti, supponiamo che che la prima volta i luoghi trovati fossero 16 mentre la seconda volta fossero 2, vengono mostrati 2 pulsanti, di cui il primo selezionato, se si va però a cambiare con il secondo il numero di pulsanti da 2 passa a 16 (Per questo suppongo che vi siano ripercussioni dovute alla selezione precedente che aveva 16 pulsanti), quando si sceglie di inviare la posizone come per i trasporti vengono inviate 2 posizioni (Con la stessa supposizione dei trasporti).

Supposizione sul bug: L'evento che si crea la prima volta resta attivo, viene creato il secondo evento per la seconda ricerca ed entrambi sono in ascolto per gli stessi comandi, ed ovviamente una volta ricevuti inviano per esempio 2 volte la posizione.

se si prova la terza volta a cercare un luogo utile/ un trasporto la posizione viene inviata 3 volte e così via.

A chi se ne occuperà il compito di confermare o semntire le mie supposizioni

**Comment by iAndrea** [comment]
## Soluzione
Attualmente si è optato per lasciare la possibilità all'utente di scegliere la fermata preferita tramite inline keyboard, e una volta deciso, tramite il pulsante "Invia posizione scelta" verrà inviata la posizione della fermata preselezionata e bloccata ogni interazione sulla scelta precedente.
Per ora quindi, si presuppone che l'utente non cambi idea in corso d'opera, dato che prima della scelta viene fornito di distanza in metri dalla fermata.
