### ISSUE TITLE
Scadenze

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#4]
Una delle cose che è maggiormente emersa dall’opinione degli studenti è che le
scadenze per la presentazione dei documenti all’Università o all’Opera Univer-
sitaria non sono sempre di facile accesso. Per informarsi e ricordarsi le date
è necessario consultare ogni singolo bando in ogni sua voce. Il nostro scopo è
portare queste informazioni nei telefoni o nei computer di ogni studente in modo
molto più pratico ed efficiente, permettendo ad ognuno di monitorare costan-
temente la propria situazione e le scadenze.

**Comment by Brugix** [comment]
Sezione Scadenza Completata.

Ora è possibile ottenere le scadenze dei vari bandi offerti dall'Università e dall'Opera Universitaria.

Tuttavia è necessario effettuare un aggiornamento manuale delle scadenze dei bandi.
