### ISSUE TITLE
Creazione casi di test

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#43]
Vanno definiti e creati casi di test in modo da verificare la correttezza del progetto, andranno utilizzati e configurati i programmi visti a lezione.

HTD: utilizzare il software visto a lezione e verificare la corretta terminazione dei casi di test

**Comment by iAndrea** [comment]
Casi di test per le sezioni Mezzi, Scadenze fatti.

**Comment by tiamilani** [comment]
Ogni componente del gruppo ha prodotto i casi di test inerenti alle proprie api, ed inserito il codice nell'apposito file, il corretto funzionamento è stato testato e grazzie alla scrittura dei casi di test è stato possibile risolvere alcune bug presenti nel codice.

Tramite il comando npm test è possibile eseguire il test che viene superato da tutte le funzionalità.
