### ISSUE TITLE
Chrome: Blocked a frame with origin "null" from accessing a cross-origin frame

### ISSUE THREAD

**Issue by Brugix** [tiamilani/ProgettoIngegneriaDelSoftware2#47]
Testando il sito utilizzando Google Chrome, provando a selezionare una qualsiasi sezione nella chat viene rilevato il seguente errore: Blocked a frame with origin "null" from accessing a cross-origin frame.

Più nello specifico,
HTD:
- Aprire il sito
- Selezionare "Mezzi"
- Selezionare "Linea"
- Click destro sulla parte destra della pagina
- Analizza elemento
- Controllare nel tab "Console"

**Comment by tiamilani** [comment]
Dopo aver testato il bug utilizzando google chrome, il suddetto bug non viene riscontrato, per cui l'issue viene chiusa e considerata risolta
