### ISSUE TITLE
Documenti

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#5]
Anche i documenti che trattano di borse di studio, bandi erasmus e posti alloggio
non sono sempre facilmente raggiungibili. Spesso si tratta di cercare in vari link
e in varie pagine, dei dipartimenti, dell’Università o del proprio corso di studi,
per poter ottenere i documenti necessari.

**Comment by iAndrea** [comment]
Come per Mensa, la sezione è stata eliminata
