### ISSUE TITLE
HotFix codice richieste non riuscite avvisi

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#50]
La sezione avvisi nel caso in cui l'url non sia ben formata ritorna un json di errore ma il codice è sempre 200, modificare questo codice ed impostarlo ad un valore di errore 400.

HTD: Inviare una richiesta tramite browser e sfruttando analizza elemento controllare il codice del pacchetto restituito

**Comment by Brugix** [comment]
Hotfix completata.

Testato il codice, se la richiesta è corretta restituisce il codice 200. Altrimenti restituisce il codice 404 (esempio: se il dipartimento richiesto non è tra quelli disponibili).
