### ISSUE TITLE
HotFix codice richieste non riuscite mezzi

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#51]
Per tutte le api della sezione mezzi modificare il codice che viene inviato da 200 a 400, in modo che venga riconosciuto l'errore nell'inserimento dei valori nei parametri

HTD: Inviare una richiesta mal formata, e tramite analizza elemento andare nella sezione rete e visionare il pacchetto

**Comment by iAndrea** [comment]
Response status aggiornato in modo corretto
