### ISSUE TITLE
Avvisi

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#6]
Un altro punto messo in evidenza dal sondaggio e la difficoltà di accesso agli
avvisi del giorno della propria facoltà. Come per le discussioni in una chat,
anche tra i tanti messaggi di avviso si può perdere di vista ciò che realmente ci
interessa.

**Comment by Brugix** [comment]
Sezione Avvisi completata.

Ora è possibile scegliere una delle facoltà disponibili e visualizzare gli aggiornamenti del giorno per quella facoltà.
