### ISSUE TITLE
Mensa

### ISSUE THREAD

**Issue by tiamilani** [tiamilani/ProgettoIngegneriaDelSoftware2#7]
Sapere qual è la mensa più vicina e vedere la situazione in tempo reale delle code
nelle mense sono due argomenti di costante interesse per tutti gli studenti, dagli
ultimi iscritti, che potrebbero non conoscere l’esistenza di una mensa a pochi
passi, ai veterani dell’Università, che vogliono scegliere il luogo e il momento
più adatto per la pausa pranzo.

**Comment by iAndrea** [comment]
La sezione è stata ridotta alla sola ricerca della mensa più vicina, dato che le altre funzioni non sono implementabili per motivi di Copyright
